---
all:
  hosts:
    mytestserver01.mydomain:
      vmware_datacenter: mydatacenter
      vmware_cluster: mycluster
      vmware_template: mytemplate
      vmware_folder: "/vm/my/folder"
      vmware_annotation: "My Annotation"
      vmware_cpus: 2
      vmware_memory_mb: 4096
      vmware_dns_domain: mydomain
      vmware_dns_servers: 
        - 127.0.0.1
        - 8.8.8.8
      vmware_disks:
        - size_gb: 20
          datastore: mydatastore
        - size_gb: 4
          datastore: mydatastoreforswap
          disk_mode: independent_persistent
      vmware_networks:
        - name: mynetworkadapter
          type: static
          ip: 1.2.3.4
          netmask: 255.255.255.0
          gateway: 1.2.3.1
          start_connected: yes
        - name: myothernetworkadapter
          type: dhcp
          start_connected: yes
